appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: ve8BXI5t4ZNRpIWoAZ6qz6ZkKr5kSo+jA1C7laJEtolM0gx05D39PW9q3wFP0AxQGsNLC99IsftYmJ4LEeYY1k7/kmq7kv7tQoID7QkBrXwZ2UVXWBtKVsYQqsxaVw6w9EwFSxId1/wq0TFjii8ah9cA6F6JwNFvrtaGrXz57qxB/QzaP059pJPPiyruqKBd431UYJ5RF+A/gDU3lBcg4SZ1JhhX3jSxeUHgpv1T/+4FeKPs01bYTuT15LSqW7KAXmEoS0rp0kal9ABP+LIKIaJYVJgmH+XuWOzMr81cgjJ7HvupQ/pAoT/UnjQrQpmB+YSxWmNohnHclFG9tf2YdyV0UTsqc2QOLzB4viH5k8n2+e+VR4alkAEVixtFo5D7KBiELs698Rs+GEOLRMuh6vifp2hExtOvC5jHi7QAA59EEo3GWK4xD1aQzxxw1MLSF/TW7QWYmE4m6sYGn6mPNBjIFg4eJHkkzmCYcjwdofwR3DEaQVCS6jhnsKDRe29LtQo81btMnQc773U92i3RJPlz/yGokiB1mLMApxtmdBWmh+lr32GpHxbgxGb7RNzImMk5Dg7agrrvRJe1PLpeiAFqziCVF6o/bdePbBOIR+vDGqIOeM0dKhnD9xF3Vp/KDwSDMA92FnvJ/fHTp2KPheC7G+gDBKOqZy1+4qje7uI=}
